TARGET=linux-gnu-libc6
PREFIX=/usr
CC=gcc
CFLAGS=-O2 -fPIC -I. -I../common
SONAME=libgelfload-native-gelfshims-linux-gnu-libc6.so.0
SOFLAGS=-shared -Wl,-soname,$(SONAME)

OBJS=start.o

all: $(SONAME)

$(SONAME): $(OBJS)
	$(CC) $(CFLAGS) $(SOFLAGS) $(OBJS) -o $(SONAME)

.SUFFIXES: .c .o

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(SONAME) $(OBJS)

install:
	install -d $(PREFIX)/lib/gelfload
	install $(SONAME) $(PREFIX)/lib/gelfload/$(SONAME)
