TARGET=linux-gnu-libc6
OBJS=\
ctype.o \
environ.o \
errno.o \
error.o \
generic.o \
gettext.o \
gmon.o \
gnu.o \
open.o \
progname.o \
readdir64.o \
rt.o \
start.o \
stat64.o \
stdio.o \
utime.o

include ../common/Makefile.common
