CC=gcc
CFLAGS=$(SCFLAGS) -O2 -g
PREFIX=/usr

all: $(SONAME)

$(SONAME): $(OBJS)
	$(CC) $(CFLAGS) $(SCFLAGS) $(SLDFLAGS) $(SONAMEFLAGS) $(OBJS) -o $(SONAME)

.SUFFIXES: .c .o

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(SONAME) $(OBJS)

install:
	install -D $(SONAME) $(PREFIX)/lib/gelfload/$(SONAME)
