CC=gcc
CFLAGS=$(SCFLAGS) -O2 -g -I../common
PREFIX=/usr
COBJS=cdirect.o cshstdio.o

all: $(SONAME)

$(SONAME): $(COBJS) $(OBJS)
	$(CC) $(CFLAGS) $(SCFLAGS) $(SLDFLAGS) $(SONAMEFLAGS) $(COBJS) $(OBJS) -o $(SONAME)

.SUFFIXES: .c .o

%.o: %.c
	$(CC) $(CFLAGS) -c $<

%.o: ../common/%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(SONAME) $(COBJS) $(OBJS)

install:
	install -D $(SONAME) $(PREFIX)/lib/gelfload/$(SONAME)
